excluded:
  - Pods
  - Market/Sources/Entries/AppDelegate.swift
  - Market/Sources/Entries/SceneDelegate.swift
disabled_rules:
  - function_parameter_count
  - trailing_whitespace
  - identifier_name
line_length: 100
